base_url = "https://joe.cargill.ie"

title = "Joe Cargill's personal blog."
description = """A personal website for writing about software engineering, 
rock-climbing, reading, and anything else"""

compile_sass = true
highlight_code = true
highlight_theme = "ayu-dark"
build_search_index = true

# Put all your custom variables here
[extra]
hyde_sticky = false
hyde_reverse = false
hyde_theme = ""
hyde_links = [
  {url = "/blog", name = "Blog"},
  {url = "/about", name = "About"},
  {url = "https://github.com/joecargill", name = "GitHub"},
  {url = "https://linkedin.com/in/joecargill", name = "LinkedIn"},
  {url = "https://drive.google.com/file/d/1I7wV0fVfiOXWz5nOLnb_lyHdqHkq1mWm/view?usp=sharing", name = "Resume", newtab = true}
]
